# Generated by Django 6.0.2 on 2026-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=10000)),
                ('director', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('dvd', 'DVD'), ('blu-ray', 'Blu-Ray')], default='dvd', max_length=10)),
                ('picture_description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('picture', models.ImageField(default=0, upload_to='images/')),
            ],
        ),
    ]
