# Generated by Django 6.0.2 on 2026-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('abenteuer', 'Abenteuer'), ('action', 'Action'), ('animation', 'Animation'), ('anime', 'Anime'), ('doku', 'Doku'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('komödie', 'Komödie'), ('krimi', 'Krimi'), ('liebesfilm', 'Liebesfilm'), ('musik', 'Musik'), ('musical', 'Musical'), ('science-fiction', 'Science-Fiction'), ('thriller', 'Thriller'), ('western', 'Western')], default='action', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=130),
        ),
        migrations.AddField(
            model_name='movie',
            name='viewed',
            field=models.CharField(choices=[('ja', 'Ja'), ('nein', 'Nein')], default='nein', max_length=10),
        ),
    ]
