# Generated by Django 6.0.2 on 2026-02-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_organizer', '0002_movie_genre_movie_runtime_movie_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('desk', 'Desk'), ('drawer', 'Drawer'), ('shelf', 'Shelf')], default='shelf', max_length=10)),
                ('levels', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_organizer.room')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('row', models.IntegerField()),
                ('home', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_organizer.movie')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_organizer.furniture')),
            ],
        ),
    ]
