# Generated by Django 6.0.2 on 2026-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_organizer', '0003_room_furniture_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.CharField(default='Keller', max_length=50),
        ),
    ]
